In [1]:
!python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 3.9 MB/s eta 0:00:00
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.10.0+cpu)
Requirement already satisfied: regex>=2022 in /usr/local/lib/python3.12/dist-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.11.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.0.3)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
!python -m spacy download fr_dep_news_trf

Collecting fr-dep-news-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/fr_dep_news_trf-3.8.0/fr_dep_news_trf-3.8.0-py3-none-any.whl (397.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 397.7/397.7 MB 1.9 MB/s eta 0:00:00
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from fr-dep-news-trf==3.8.0) (0.3.1)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from fr-dep-news-trf==3.8.0) (0.2.1)
Collecting protobuf<3.21.0 (from fr-dep-news-trf==3.8.0)
  Downloading protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (2.10.0+cpu)
Requirement already satisfied: regex>=2022 in /usr/local/lib/python3.12/dist-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (2025.11.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->fr-dep-news-trf==3.8.0) (3.0.3)
Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 2.4 MB/s eta 0:00:00
Installing collected packages: protobuf, fr-dep-news-trf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grain 0.2.16 requires protobuf>=5.28.3, but you have protobuf 3.20.3 which is incompatible.
tensorflow-metadata 1.17.3 requires protobuf>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.3 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 3.20.3 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 3.20.3 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.3 which is incompatible.
google-api-core 2.30.0 requires protobuf<7.0.0,>=4.25.8, but you have protobuf 3.20.3 which is incompatible.
Successfully installed fr-dep-news-trf-3.8.0 protobuf-3.20.3
✔ Download and installation successful
You can now load the package via spacy.load('fr_dep_news_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
import en_core_web_trf
nlp_en = en_core_web_trf.load()

In [4]:
import fr_dep_news_trf
nlp_fr = fr_dep_news_trf.load()

In [5]:
pip install wn

Collecting wn
  Downloading wn-1.0.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from wn) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->wn) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->wn) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->wn) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->wn) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->wn) (0.16.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx->wn) (4.15.0)
Downloading wn-1.0.0-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.5/94.5 kB 1.8 MB/s eta 0:00:00
Installing collected packages: wn
Successfully installed wn-1.0.0

In [6]:
import wn

In [7]:
!python3 -m wn download omw:1.4

Download [##############################] (49414200/49414200 bytes) Complete
Read [##############################] (18532/18532)
Added omw-nb:1.4 (Norwegian Wordnet (Bokmål))
Read [##############################] (83267/83267)
Added omw-arb:1.4 (Arabic WordNet (AWN v2))
Read [##############################] (231871/231871)
Added omw-id:1.4 (Wordnet Bahasa (Indonesian))
Read [##############################] (92417/92417)
Added omw-iwn:1.4 (ItalWordNet)
Read [##############################] (131130/131130)
Added omw-eu:1.4 (Multilingual Central Repository (Basque))
Read [##############################] (567477/567477)
Added omw-fi:1.4 (FinnWordNet)
Read [##############################] (301893/301893)
Added omw-ro:1.4 (Romanian Wordnet)
Read [##############################] (44268/44268)
Added omw-is:1.4 (IceWordNet)
Read [##############################] (15308/15308)
Added omw-nn:1.4 (Norwegian Wordnet (Nynorsk))
Read [##############################] (46814/46814)
Added omw-bg:1.4 (BulTreeBank Wordnet (BTB-WN))
Read [##############################] (211647/211647)
Added omw-ca:1.4 (Multilingual Central Repository (Catalan))
Read [##############################] (48353/48353)
Added omw-lt:1.4 (Lithuanian  WordNet)
Read [##############################] (227774/227774)
Added omw-pt:1.4 (OpenWN-PT)
Read [##############################] (96758/96758)
Added omw-el:1.4 (Greek Wordnet)
Read [##############################] (129201/129201)
Added omw-hr:1.4 (Croatian Wordnet)
Read [##############################] (335832/335832)
Added omw-th:1.4 (Thai Wordnet)
Read [##############################] (177773/177773)
Added omw-nl:1.4 (Open Dutch WordNet)
Read [##############################] (188283/188283)
Added omw-it:1.4 (MultiWordNet (Italian))
Read [##############################] (93273/93273)
Added omw-gl:1.4 (Multilingual Central Repository (Galician))
Read [##############################] (120995/120995)
Added omw-sk:1.4 (Slovak WordNet)
Read [##############################] (248818/248818)
Added omw-cmn:1.4 (Chinese Open Wordnet)
Read [##############################] (35257/35257)
Added omw-sq:1.4 (Albanet)
Read [##############################] (19380/19380)
Added omw-da:1.4 (DanNet)
Read [##############################] (219452/219452)
Added omw-zsm:1.4 (Wordnet Bahasa (Malaysian))
Read [##############################] (25447/25447)
Added omw-sv:1.4 (WordNet-SALDO)
Read [##############################] (280977/280977)
Added omw-fr:1.4 (WOLF (Wordnet Libre du Français))
Read [##############################] (177117/177117)
Added omw-pl:1.4 (plWordNet)
Read [##############################] (201542/201542)
Added omw-sl:1.4 (sloWNet)
Read [##############################] (170685/170685)
Added omw-es:1.4 (Multilingual Central Repository (Spanish))
Read [##############################] (1221564/1221564)
Added omw-en:1.4 (OMW English Wordnet based on WordNet 3.0)
Read [##############################] (29690/29690)
Added omw-he:1.4 (Hebrew Wordnet)
Read [##############################] (499566/499566)
Added omw-ja:1.4 (Japanese Wordnet)

In [8]:
en=wn.Wordnet('omw-en:1.4')

In [9]:
fr=wn.Wordnet('omw-fr:1.4')

In [10]:
ch=wn.Wordnet('omw-cmn:1.4')

In [11]:
jp=wn.Wordnet('omw-ja:1.4')

In [12]:
import spacy
import pandas as pd

In [13]:
!gdown 18kaAF4q_X6Kgtjh16SUpZIagFTQ2O4un

Downloading...
From: https://drive.google.com/uc?id=18kaAF4q_X6Kgtjh16SUpZIagFTQ2O4un
To: /content/nouns_checked.csv
100% 227k/227k [00:00<00:00, 7.74MB/s]

In [14]:
!gdown 1qNIPTVBC-17UfJoDYJfHtuKtn6DLI4Yh

Downloading...
From: https://drive.google.com/uc?id=1qNIPTVBC-17UfJoDYJfHtuKtn6DLI4Yh
To: /content/verbs_checked.csv
100% 75.7k/75.7k [00:00<00:00, 6.52MB/s]

In [116]:
nouns=pd.read_csv("nouns_checked.csv")

In [109]:
verbs=pd.read_csv("verbs_checked.csv",names=list(nouns.columns.values))

In [67]:
verbs

,Word,Freq,Unnamed: 2,Unnamed: 3,Unnamed: 4,PERCENTAGE OF NOUNS,Unnamed: 6,Include
0,'s,56387.0,NaN,NaN,6.645732,NaN,NaN,NaN
1,do,28698.0,NaN,NaN,5.813916,NaN,NaN,NaN
2,is,25106.0,NaN,NaN,4.181777,NaN,NaN,NaN
3,are,18058.0,NaN,NaN,2.809465,NaN,NaN,NaN
4,'re,12132.0,NaN,NaN,2.531112,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2944,huddle,1.0,NaN,NaN,0.000232,NaN,NaN,NaN
2945,shatter,1.0,NaN,NaN,0.000232,NaN,NaN,NaN
2946,align,1.0,NaN,NaN,0.000000,NaN,NaN,NaN
2947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2948,NaN,431826.0,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [35]:
len(verbs['Word'])

2949

In [90]:
syn_nltk

[Synset('align.v.01'),
 Synset('align.v.02'),
 Synset('align.v.03'),
 Synset('align.v.04')]

In [94]:
syn_nltk[2]

Synset('align.v.03')

In [110]:
from nltk.corpus import wordnet as nltk_wn
from collections import defaultdict
d= defaultdict(int)
d_classes= defaultdict(int)
validity=[""]*verbs.shape[0]
for i in range(verbs.shape[0]):
    word=str(verbs.iloc[i,0])
    #print(word)
    word=nlp_en(word)
    lemma=word[0].lemma_
    #print(lemma)
    syn =  en.synsets(lemma, pos='v')
    #syn =  en.synsets(lemma, pos='v')
    syn_nltk=nltk_wn.synsets(lemma,pos='v')
    classes=[]
    if len(syn) > 0:
      for i in range(len(syn)):
          #d[syn_nltk[i].lexname()].append(lemma)
          classes.append(syn_nltk[i].lexname())
          #classes.append(syn_nltk[0].lexname())
    d_classes[lemma]=set(classes)
    #print(set(classes))
    if len(set(classes).intersection(["verb.motion","verb.body","verb.consumption","verb.competition","verb.communication"])) > 0:
    #if len(set(classes).intersection(["verb.motion"])) > 0:
          #print("INC")
          d[lemma] = 1
    else:
          d[lemma] = 0

In [111]:
verbs=verbs.merge(pd.DataFrame(d.items(),columns=["Word","Include"]),left_on='Word',right_on='Word')

In [89]:
d_classes["will"]

{'verb.cognition', 'verb.communication', 'verb.possession'}

In [112]:
verbs.head(50)

,Word,Freq,Unnamed: 2,Unnamed: 3,Unnamed: 4,PERCENTAGE OF NOUNS,Unnamed: 6,Include_x,Include_y
0,'s,56387.0,NaN,NaN,6.645732,NaN,NaN,NaN,0
1,do,28698.0,NaN,NaN,5.813916,NaN,NaN,NaN,1
2,have,10930.0,NaN,NaN,2.416714,NaN,NaN,NaN,1
3,can,10436.0,NaN,NaN,2.296527,NaN,NaN,NaN,0
4,got,9369.0,NaN,NaN,2.088110,NaN,NaN,NaN,1
5,go,9017.0,NaN,NaN,2.002195,NaN,NaN,NaN,1
6,put,8646.0,NaN,NaN,1.825041,NaN,NaN,NaN,1
7,think,7881.0,NaN,NaN,1.643254,NaN,NaN,NaN,0
8,look,7096.0,NaN,NaN,1.635844,NaN,NaN,NaN,1
9,get,5614.0,NaN,NaN,1.275514,NaN,NaN,NaN,1
10,shall,5434.0,NaN,NaN,1.252125,NaN,NaN,NaN,0
11,see,5407.0,NaN,NaN,1.237999,NaN,NaN,NaN,1
12,come,5346.0,NaN,NaN,1.145369,NaN,NaN,NaN,1
13,want,4946.0,NaN,NaN,1.088864,NaN,NaN,NaN,1
14,be,4702.0,NaN,NaN,1.039076,NaN,NaN,NaN,0
15,know,4487.0,NaN,NaN,0.793375,NaN,NaN,NaN,0
16,like,3401.0,NaN,NaN,0.759102,NaN,NaN,NaN,0
17,let,3278.0,NaN,NaN,0.710008,NaN,NaN,NaN,1
18,wanna,2903.0,NaN,NaN,0.670409,NaN,NaN,NaN,0
19,ca,2895.0,NaN,NaN,0.578705,NaN,NaN,NaN,0
20,make,2499.0,NaN,NaN,0.536559,NaN,NaN,NaN,1
21,say,2317.0,NaN,NaN,0.520580,NaN,NaN,NaN,1
22,play,2248.0,NaN,NaN,0.508307,NaN,NaN,NaN,1
23,wo,2175.0,NaN,NaN,0.466623,NaN,NaN,NaN,0
24,hafta,2015.0,NaN,NaN,0.461528,NaN,NaN,NaN,0
25,take,1993.0,NaN,NaN,0.432582,NaN,NaN,NaN,1
26,will,1868.0,NaN,NaN,0.415677,NaN,NaN,NaN,1
27,would,1795.0,NaN,NaN,0.405256,NaN,NaN,NaN,0
28,find,1750.0,NaN,NaN,0.391361,NaN,NaN,NaN,1
29,could,1584.0,NaN,NaN,0.348520,NaN,NaN,NaN,0
30,sit,1505.0,NaN,NaN,0.329762,NaN,NaN,NaN,1
31,eat,1424.0,NaN,NaN,0.312394,NaN,NaN,NaN,1
32,tell,1349.0,NaN,NaN,0.308226,NaN,NaN,NaN,1
33,need,1331.0,NaN,NaN,0.307994,NaN,NaN,NaN,1
34,might,1313.0,NaN,NaN,0.289005,NaN,NaN,NaN,0
35,give,1248.0,NaN,NaN,0.287847,NaN,NaN,NaN,1
36,'d,1192.0,NaN,NaN,0.256585,NaN,NaN,NaN,0
37,remember,1108.0,NaN,NaN,0.229954,NaN,NaN,NaN,1
38,fit,993.0,NaN,NaN,0.225091,NaN,NaN,NaN,0
39,should,869.0,NaN,NaN,0.191512,NaN,NaN,NaN,0
40,thought,782.0,NaN,NaN,0.178776,NaN,NaN,NaN,0
41,draw,772.0,NaN,NaN,0.171828,NaN,NaN,NaN,1
42,pull,715.0,NaN,NaN,0.159323,NaN,NaN,NaN,1
43,try,688.0,NaN,NaN,0.151913,NaN,NaN,NaN,1
44,help,656.0,NaN,NaN,0.149597,NaN,NaN,NaN,1
45,keep,646.0,NaN,NaN,0.149366,NaN,NaN,NaN,1
46,turn,645.0,NaN,NaN,0.147050,NaN,NaN,NaN,1
47,show,631.0,NaN,NaN,0.145661,NaN,NaN,NaN,1
48,fall,623.0,NaN,NaN,0.143808,NaN,NaN,NaN,1
49,move,621.0,NaN,NaN,0.140797,NaN,NaN,NaN,1

In [118]:
nouns.shape[0]

7980

In [120]:
d= defaultdict(int)
for i in range(nouns.shape[0]):
    word=str(nouns.iloc[i,0])
    #print(word)
    word=nlp_en(word)
    lemma=word[0].lemma_
    #print(lemma)
    syn =  en.synsets(lemma, pos='n')
    if len(syn) > 0:
      this_word = syn[0]
      lem=[]
      for path in wn.taxonomy.hypernym_paths(this_word):
         for i, ss in enumerate(path):
            lem.extend([l for l in ss.lemmas()])
      #print(lem)
      if ("physical entity" in lem):
          d[lemma] = 1
      else:
         d[lemma] = 0
      #nouns.iloc[i,7] = ("physical entity" in lem)

In [121]:
nouns=nouns.merge(pd.DataFrame(d.items(),columns=["Word","Include"]),left_on='Word',right_on='Word')

In [122]:
nouns.shape

(3429, 8)

In [123]:
nouns.to_csv("noun_selection.csv")

In [124]:
verbs.to_csv("verb_selection.csv")

In [125]:
ls

nouns_checked.csv   sample_data/       verb_selection.csv
noun_selection.csv  verbs_checked.csv

In [126]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [132]:
!cp noun_selection.csv /content/drive/MyDrive/Research/Projects/Perrine_Categories/NVModel/

# New section

French

In [ ]:
ss=syns[8].translate(lexicon='omw-en:1.4')[0]

In [ ]:
import nltk
from nltk.corpus import wordnet

In [ ]:
word="chat"
word=nlp_fr(word)
lemma=word[0].lemma_
print(word)
syns=fr.synsets(lemma, pos='n')
for this_word in syns:
  print(this_word.lemmas())
  for path in wn.taxonomy.hypernym_paths(this_word):
    for i, ss in enumerate(path):

            print(this_word.lemmas())
            #lem.extend([l for l in ss.lemmas()])
            #print(ss.lemmas())
            lem.append([l for l in ss.lemmas()])


#print(lem)
#print("entité" in lem)

In [ ]:
word="chat"
word=nlp_fr(word)
lemma=word[0].lemma_

In [ ]:
lemma.count()

In [ ]:
fr.synsets(lemma, pos='n')

In [ ]:
syns

In [ ]:
syns[i].translate(lexicon='omw-en:1.4')[0].lemmas()

In [ ]:
[nltk_wn.synsets(l,pos='v') for l in syn_en.lemmas()]

In [ ]:

word="venir"
word=nlp_fr(word)
lemma=word[0].lemma_
syns = fr.synsets(lemma, pos='v')
classes=[]
if len(syns) > 0:
      for i in range(len(syns)):
          syn_en=syns[i].translate(lexicon='omw-en:1.4')[0]
          syn_nltk=[nltk_wn.synsets(l,pos='v') for l in syn_en.lemmas]
          #d[syn_nltk[i].lexname()].append(lemma)
          classes.append(syn_nltk.lexname())
      if len(set(classes).intersection(["verb.motion"])) > 0:
          print("INC")
          #d[lemma] = 1
      else:
          print("EXCL")
          #d[lemma] = 0